//
//  Themes.swift
//  Wordy
//
//  Created by Vlad Sytnik on 18.09.2023.
//

import SwiftUI


struct Themes {
	static let availableThemes: [ColorTheme] = [
        ColorTheme(isFree: true,
                   isDark: true,
                   isSupportLightTheme: true,
				   id: "MainColor",
				   accent: Color(asset: Asset.Colors.accent),
				   main: Color(asset: Asset.Colors.main),
				   darkMain: Color(asset: Asset.Colors.darkMain),
				   mainText: Color(asset: Asset.Colors.mainTextColor),
				   findedWordsHighlited: Color(asset: Asset.Colors.findedWordHighlite),
				   brightForBtnsText: Color(asset: Asset.Colors.brightBtnText),
				   moduleCreatingBtn: Color(asset: Asset.Colors.addModuleButtonBG),
				   mainGray: Color(asset: Asset.Colors.createModuleButton),
				   purchaseBtn: Color(asset: Asset.Colors.purchaseBtn),
				   learnModuleBtnText: Color(asset: Asset.Colors.learnModuleBtnText),
				   searchTextFieldBG: Color(asset: Asset.Colors.searchTFBackground),
				   searchTextFieldText: Color(asset: Asset.Colors.searchTextFieldTextColor),
				   moduleCardRoundedAreaColor: Color(asset: Asset.Colors.moduleCardRoundedAreaColor),
				   nonActiveCategory: Color(asset: Asset.Colors.nonActiveCategory),
                   carouselLearnBtnColor: Color(asset: Asset.Colors.carouselLearnBtnColor),
                   paywallBtnsColor: Color(asset: Asset.Colors.paywallBtnsColor),
                   moduleScreenBtnsColor: Color(asset: Asset.Colors.moduleScreenBtns),
                   
				   answer1: Color(asset: Asset.Colors.answer1),
				   answer2: Color(asset: Asset.Colors.answer2),
				   answer3: Color(asset: Asset.Colors.answer3),
				   answer4: Color(asset: Asset.Colors.answer4),
                   
                   moduleCardMainTextColor: Color(asset: Asset.Colors.moduleCardMainTextColor),
                   gradientStart: Color(asset: Asset.Colors.gradientStart),
                   gradientEnd: Color(asset: Asset.Colors.gradientEnd),
				   
				   mainBackgroundImage: Image(asset: Asset.Images.gradientBG),
				   carouselCardBackgroundImage: Image(asset: Asset.Images.carouselBG),
				   authBackgroundImage: Image(asset: Asset.Images.authBG),
				   learnPageBackgroundImage: Image(asset: Asset.Images.learnPageBG)),
		
		ColorTheme(isFree: true,
                   isDark: true,
                   isSupportLightTheme: false,
				   id: "RedColor",
				   accent: Color(asset: Asset.Colors2.accent2),
				   main: Color(asset: Asset.Colors2.main2),
				   darkMain: Color(asset: Asset.Colors2.darkMain2),
				   mainText: Color(asset: Asset.Colors2.mainTextColor2),
				   findedWordsHighlited: Color(asset: Asset.Colors2.findedWordHighlite2),
				   brightForBtnsText: Color(asset: Asset.Colors2.brightBtnText2),
				   moduleCreatingBtn: Color(asset: Asset.Colors2.addModuleButtonBG2),
				   mainGray: Color(asset: Asset.Colors2.createModuleButton2),
				   purchaseBtn: Color(asset: Asset.Colors2.purchaseBtn2),
				   learnModuleBtnText: Color(asset: Asset.Colors2.learnModuleBtnText2),
				   searchTextFieldBG: Color(asset: Asset.Colors2.searchTFBackground2),
				   searchTextFieldText: Color(asset: Asset.Colors2.searchTextFieldTextColor2),
				   moduleCardRoundedAreaColor: Color(asset: Asset.Colors2.moduleCardRoundedAreaColor2),
				   nonActiveCategory: Color(asset: Asset.Colors2.nonActiveCategory2),
                   carouselLearnBtnColor: Color(asset: Asset.Colors2.carouselLearnBtnColor2),
                   paywallBtnsColor: Color(asset: Asset.Colors2.paywallBtnsColor2),
                   moduleScreenBtnsColor: Color(asset: Asset.Colors2.moduleScreenBtns2),
                   
				   answer1: Color(asset: Asset.Colors2.answer12),
				   answer2: Color(asset: Asset.Colors2.answer22),
				   answer3: Color(asset: Asset.Colors2.answer32),
				   answer4: Color(asset: Asset.Colors2.answer42),
                   
                   moduleCardMainTextColor: Color(asset: Asset.Colors2.moduleCardMainTextColor2),
				   
				   mainBackgroundImage: Image(asset: Asset.Images2.gradientBG2),
				   carouselCardBackgroundImage: Image(asset: Asset.Images2.carouselBG2),
				   authBackgroundImage: Image(asset: Asset.Images2.authBG2),
				   learnPageBackgroundImage: Image(asset: Asset.Images2.learnPageBG2)),
		
		ColorTheme(isFree: false,
                   isDark: false,
                   isSupportLightTheme: false,
				   id: "LightPinkColor",
				   accent: Color(asset: Asset.Colors3.accent3),
				   main: Color(asset: Asset.Colors3.main3),
				   darkMain: Color(asset: Asset.Colors3.darkMain3),
				   mainText: Color(asset: Asset.Colors3.mainTextColor3),
				   findedWordsHighlited: Color(asset: Asset.Colors3.findedWordHighlite3),
				   brightForBtnsText: Color(asset: Asset.Colors3.brightBtnText3),
				   moduleCreatingBtn: Color(asset: Asset.Colors3.addModuleButtonBG3),
				   mainGray: Color(asset: Asset.Colors3.createModuleButton3),
				   purchaseBtn: Color(asset: Asset.Colors3.purchaseBtn3),
				   learnModuleBtnText: Color(asset: Asset.Colors3.learnModuleBtnText3),
				   searchTextFieldBG: Color(asset: Asset.Colors3.searchTFBackground3),
				   searchTextFieldText: Color(asset: Asset.Colors3.searchTextFieldTextColor3),
				   moduleCardRoundedAreaColor: Color(asset: Asset.Colors3.moduleCardRoundedAreaColor3),
				   nonActiveCategory: Color(asset: Asset.Colors3.nonActiveCategory3),
                   carouselLearnBtnColor: Color(asset: Asset.Colors3.carouselLearnBtnColor3),
                   paywallBtnsColor: Color(asset: Asset.Colors3.paywallBtnsColor3),
                   moduleScreenBtnsColor: Color(asset: Asset.Colors3.moduleScreenBtns3),
                   
				   answer1: Color(asset: Asset.Colors3.answer13),
				   answer2: Color(asset: Asset.Colors3.answer23),
				   answer3: Color(asset: Asset.Colors3.answer33),
                   answer4: Color(asset: Asset.Colors3.answer43),
                   
                   moduleCardMainTextColor: Color(asset: Asset.Colors3.moduleCardMainTextColor3),
                   
				   
				   mainBackgroundImage: Image(asset: Asset.Images3.gradientBG3),
				   carouselCardBackgroundImage: Image(asset: Asset.Images3.carouselBG3),
				   authBackgroundImage: Image(asset: Asset.Images3.authBG3),
				   learnPageBackgroundImage: Image(asset: Asset.Images3.learnPageBG3)),
        
        ColorTheme(isFree: false,
                   isDark: false,
                   isSupportLightTheme: false,
                   id: "LightPastilleBlue",
                   accent: Color(asset: Asset.Colors4.accent4),
                   main: Color(asset: Asset.Colors4.main4),
                   darkMain: Color(asset: Asset.Colors4.darkMain4),
                   mainText: Color(asset: Asset.Colors4.mainTextColor4),
                   findedWordsHighlited: Color(asset: Asset.Colors4.findedWordHighlite4),
                   brightForBtnsText: Color(asset: Asset.Colors4.brightBtnText4),
                   moduleCreatingBtn: Color(asset: Asset.Colors4.addModuleButtonBG4),
                   mainGray: Color(asset: Asset.Colors4.createModuleButton4),
                   purchaseBtn: Color(asset: Asset.Colors4.purchaseBtn4),
                   learnModuleBtnText: Color(asset: Asset.Colors4.learnModuleBtnText4),
                   searchTextFieldBG: Color(asset: Asset.Colors4.searchTFBackground4),
                   searchTextFieldText: Color(asset: Asset.Colors4.searchTextFieldTextColor4),
                   moduleCardRoundedAreaColor: Color(asset: Asset.Colors4.moduleCardRoundedAreaColor4),
                   nonActiveCategory: Color(asset: Asset.Colors4.nonActiveCategory4),
                   carouselLearnBtnColor: Color(asset: Asset.Colors4.carouselLearnBtnColor4),
                   paywallBtnsColor: Color(asset: Asset.Colors4.paywallBtnsColor4),
                   moduleScreenBtnsColor: Color(asset: Asset.Colors4.moduleScreenBtns4),
                   
                   answer1: Color(asset: Asset.Colors4.answer14),
                   answer2: Color(asset: Asset.Colors4.answer24),
                   answer3: Color(asset: Asset.Colors4.answer34),
                   answer4: Color(asset: Asset.Colors4.answer44),
                   
                   moduleCardMainTextColor: Color(asset: Asset.Colors4.moduleCardMainTextColor4),
                   
                   mainBackgroundImage: Image(asset: Asset.Images4.gradientBG4),
                   carouselCardBackgroundImage: Image(asset: Asset.Images4.carouselBG4),
                   authBackgroundImage: Image(asset: Asset.Images4.authBG4),
                   learnPageBackgroundImage: Image(asset: Asset.Images4.learnPageBG4)),
        
        ColorTheme(isFree: false,
                   isDark: false,
                   isSupportLightTheme: false,
                   id: "LightPastillePeach",
                   accent: Color(asset: Asset.Colors5.accent5),
                   main: Color(asset: Asset.Colors5.main5),
                   darkMain: Color(asset: Asset.Colors5.darkMain5),
                   mainText: Color(asset: Asset.Colors5.mainTextColor5),
                   findedWordsHighlited: Color(asset: Asset.Colors5.findedWordHighlite5),
                   brightForBtnsText: Color(asset: Asset.Colors5.brightBtnText5),
                   moduleCreatingBtn: Color(asset: Asset.Colors5.addModuleButtonBG5),
                   mainGray: Color(asset: Asset.Colors5.createModuleButton5),
                   purchaseBtn: Color(asset: Asset.Colors5.purchaseBtn5),
                   learnModuleBtnText: Color(asset: Asset.Colors5.learnModuleBtnText5),
                   searchTextFieldBG: Color(asset: Asset.Colors5.searchTFBackground5),
                   searchTextFieldText: Color(asset: Asset.Colors5.searchTextFieldTextColor5),
                   moduleCardRoundedAreaColor: Color(asset: Asset.Colors5.moduleCardRoundedAreaColor5),
                   nonActiveCategory: Color(asset: Asset.Colors5.nonActiveCategory5),
                   carouselLearnBtnColor: Color(asset: Asset.Colors5.carouselLearnBtnColor5),
                   paywallBtnsColor: Color(asset: Asset.Colors5.paywallBtnsColor5),
                   moduleScreenBtnsColor: Color(asset: Asset.Colors5.moduleScreenBtns5),
                   
                   answer1: Color(asset: Asset.Colors5.answer15),
                   answer2: Color(asset: Asset.Colors5.answer25),
                   answer3: Color(asset: Asset.Colors5.answer35),
                   answer4: Color(asset: Asset.Colors5.answer45),
                   
                   moduleCardMainTextColor: Color(asset: Asset.Colors5.moduleCardMainTextColor5),
                   
                   mainBackgroundImage: Image(asset: Asset.Images5.gradientBG5),
                   carouselCardBackgroundImage: Image(asset: Asset.Images5.carouselBG5),
                   authBackgroundImage: Image(asset: Asset.Images5.authBG5),
                   learnPageBackgroundImage: Image(asset: Asset.Images5.learnPageBG5)),
        
        ColorTheme(isFree: false,
                   isDark: true,
                   isSupportLightTheme: false,
                   id: "DarkMint",
                   accent: Color(asset: Asset.Colors6.accent6),
                   main: Color(asset: Asset.Colors6.main6),
                   darkMain: Color(asset: Asset.Colors6.darkMain6),
                   mainText: Color(asset: Asset.Colors6.mainTextColor6),
                   findedWordsHighlited: Color(asset: Asset.Colors6.findedWordHighlite6),
                   brightForBtnsText: Color(asset: Asset.Colors6.brightBtnText6),
                   moduleCreatingBtn: Color(asset: Asset.Colors6.addModuleButtonBG6),
                   mainGray: Color(asset: Asset.Colors6.createModuleButton6),
                   purchaseBtn: Color(asset: Asset.Colors6.purchaseBtn6),
                   learnModuleBtnText: Color(asset: Asset.Colors6.learnModuleBtnText6),
                   searchTextFieldBG: Color(asset: Asset.Colors6.searchTFBackground6),
                   searchTextFieldText: Color(asset: Asset.Colors6.searchTextFieldTextColor6),
                   moduleCardRoundedAreaColor: Color(asset: Asset.Colors6.moduleCardRoundedAreaColor6),
                   nonActiveCategory: Color(asset: Asset.Colors6.nonActiveCategory6),
                   carouselLearnBtnColor: Color(asset: Asset.Colors6.carouselLearnBtnColor6),
                   paywallBtnsColor: Color(asset: Asset.Colors6.paywallBtnsColor6),
                   moduleScreenBtnsColor: Color(asset: Asset.Colors6.moduleScreenBtns6),
                   
                   answer1: Color(asset: Asset.Colors6.answer16),
                   answer2: Color(asset: Asset.Colors6.answer26),
                   answer3: Color(asset: Asset.Colors6.answer36),
                   answer4: Color(asset: Asset.Colors6.answer46),
                   
                   moduleCardMainTextColor: Color(asset: Asset.Colors6.moduleCardMainTextColor6),
                   
                   mainBackgroundImage: Image(asset: Asset.Images6.gradientBG6),
                   carouselCardBackgroundImage: Image(asset: Asset.Images6.carouselBG6),
                   authBackgroundImage: Image(asset: Asset.Images6.authBG6),
                   learnPageBackgroundImage: Image(asset: Asset.Images6.learnPageBG6))
	]
}
